
import "use client";
import BentoBoxItem from './BentoBoxItem';

export default function BentoBox() {
  const features = [
    { title: 'AI Artistry', description: 'Experience cutting-edge digital art generated by AI models.' },
    { title: 'Predictive Analytics', description: 'Utilize AI-driven insights for forward-thinking business strategies.' },
    { title: 'Automation Tools', description: 'Enhance productivity with intelligent automation solutions.' }
  ];

  return (
    <div className="bento-box">
      {features.map((feature, index) => (
        <BentoBoxItem key={index} title={feature.title} description={feature.description} />
      ))}
    </div>
  );
}
